# Generated by Django 5.1.6 on 2025-02-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.CharField(default=12, max_length=32),
            preserve_default=False,
        ),
    ]
