# Generated by Django 5.1.6 on 2025-02-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group',
            new_name='room_name',
        ),
    ]
